apiVersion: v1
kind: ConfigMap
metadata:
  name: node-app-config
data:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_PORT: "5000"
  MONGO_URL: "mongodb://mongo:27017/database"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: omarismail0/kubernetes-project:back-end
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /data
              name: node-app-storage
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: node-app-storage
          persistentVolumeClaim:
            claimName: node-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: prod
spec:
  type: ExternalName
  externakName: node-app.prod.svc.cluster.local
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    app: node-app
